---
engines:
  scss-lint:
    enabled: true
  bundler-audit:
    enabled: true
ratings:
  paths:
  - "source/stylesheets/*.scss"

exclude_paths:
- "config/"
- "source/javascripts/"
- "source/stylesheets/animate.css"
